### ISSUE TITLE
Autocompletion and hovers fail with NullPointerException

### ISSUE THREAD

**Issue by felixfbecker** [angelozerr/lsp4xml#108]
I am using [vscode-xml](https://github.com/redhat-developer/vscode-xml), but hovers or completion don't work and log this to the output channel:

Hover:
```
Sep 09, 2018 4:43:01 PM org.eclipse.lsp4xml.services.XMLHover getTagHover
SEVERE: While performing IHoverParticipant#onTag
java.lang.NullPointerException
	at org.eclipse.lsp4xml.contentmodel.xsd.XSDDocument.findCMElement(XSDDocument.java:63)
	at org.eclipse.lsp4xml.contentmodel.model.ContentModelManager.findCMElement(ContentModelManager.java:73)
	at org.eclipse.lsp4xml.contentmodel.model.ContentModelManager.findCMElement(ContentModelManager.java:61)
	at org.eclipse.lsp4xml.contentmodel.participants.ContentModelHoverParticipant.onTag(ContentModelHoverParticipant.java:31)
	at org.eclipse.lsp4xml.services.XMLHover.getTagHover(XMLHover.java:73)
	at org.eclipse.lsp4xml.services.XMLHover.doHover(XMLHover.java:56)
	at org.eclipse.lsp4xml.services.XMLLanguageService.doHover(XMLLanguageService.java:87)
	at org.eclipse.lsp4xml.XMLTextDocumentService.lambda$hover$2(XMLTextDocumentService.java:146)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Completion:
```
Sep 09, 2018 4:43:26 PM org.eclipse.lsp4xml.services.XMLCompletions collectOpenTagSuggestions
SEVERE: While performing ICompletionParticipant#onTagOpen
java.lang.NullPointerException
	at org.eclipse.lsp4xml.contentmodel.xsd.XSDDocument.findCMElement(XSDDocument.java:63)
	at org.eclipse.lsp4xml.contentmodel.model.ContentModelManager.findCMElement(ContentModelManager.java:73)
	at org.eclipse.lsp4xml.contentmodel.model.ContentModelManager.findCMElement(ContentModelManager.java:61)
	at org.eclipse.lsp4xml.contentmodel.participants.ContentModelCompletionParticipant.onTagOpen(ContentModelCompletionParticipant.java:46)
	at org.eclipse.lsp4xml.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:262)
	at org.eclipse.lsp4xml.services.XMLCompletions.collectTagSuggestions(XMLCompletions.java:251)
	at org.eclipse.lsp4xml.services.XMLCompletions.doComplete(XMLCompletions.java:82)
	at org.eclipse.lsp4xml.services.XMLLanguageService.doComplete(XMLLanguageService.java:83)
	at org.eclipse.lsp4xml.XMLTextDocumentService.lambda$completion$1(XMLTextDocumentService.java:135)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by fbricon** [comment]
Are you using an xsd? Can you please provide a sample document reproducing the problems?

**Comment by felixfbecker** [comment]
Sure, just pushed them to this repo: https://github.com/felixfbecker/PowerShellXSD

`Format.xsd` is the the schema (I autogenerated it from the XML, so pretty sure it's valid)
`TestFormat.xml` is a schema instance. Try hovering over any tag, or triggering autocompletion, and you should see the above exceptions logged (and no hover/completion results).

**Comment by fbricon** [comment]
Have you checked with the latest build?

**Comment by felixfbecker** [comment]
Yep, I can reproduce this with `vscode-xml-0.1.0-196.vsix`

**Comment by angelozerr** [comment]
`xsi:noNamespaceSchemaLocation` was not supported with completion, hover, it should be fixed now:

 * NPE should not occur
 * completion, hover (if there are documentation) should work.

**Comment by angelozerr** [comment]
I close this issue, if you have problem again, please reopen it.

**Comment by felixfbecker** [comment]
Awesome. In which version of vscode-xml can I try this out?

**Comment by fbricon** [comment]
@felixfbecker vscode-xml rebuilds every time a commit is added to the server repo. So look for the latest build in http://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D, about 15-30min after a fix is done server-side.

**Comment by angelozerr** [comment]
I don't the build process of vscode-xml, @fbricon could you give us more info about that?

**Comment by felixfbecker** [comment]
Awesome, `vscode-xml-0.1.0-199.vsix` works.

**Comment by angelozerr** [comment]
Thans @fbricon for your answer. @felixfbecker please tell me it works for you.

You should have completion like this:

![nonsdemo](https://user-images.githubusercontent.com/1932211/45297052-5d067100-b504-11e8-801a-1eff4b81cb06.gif)
