### ISSUE TITLE
multiple NPEs while editing a file, after changing the formatting preference

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#138]
In vscode, I opened a document, to check formatting was disabled with "xml.format.enabled": false, then I switched to open the settings to switch to "xml.format.enabled": true. Once I returned to the document, the server started spitting NPEs left and right.
```
Params: {
    "textDocument": {
        "uri": "file:///Users/fbricon/Downloads/sample-resources%203/multiple_namespaces/service.xsd"
    }
}


[Trace - 9:49:00 AM] Received response 'textDocument/documentLink - (68)' in 1ms.
Result: []


[Trace - 9:49:03 AM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///Users/fbricon/Downloads/sample-resources%203/multiple_namespaces/service.xsd",
        "version": 11
    },
    "contentChanges": [
        {
            "text": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<schema targetNamespace=\"http://service\" elementFormDefault=\"qualified\" xmlns=\"http://www.w3.org/2001/XMLSchema\" xmlns:tns=\"http://service\">\n    <complexType name=\"service\">\n        <attribute name=\"name\" type=\"string\" use=\"required\"></attribute>\n                  <attribute name=\"description\" type=\"string\" use=\"required\"></attribute>\n    </complexType>\n    <element name=\"service\" type=\"tns:service\"></element>\n</schema>       "
        }
    ]
}


[Trace - 9:49:03 AM] Sending request 'textDocument/foldingRange - (69)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/fbricon/Downloads/sample-resources%203/multiple_namespaces/service.xsd"
    }
}


[Trace - 9:49:03 AM] Received response 'textDocument/foldingRange - (69)' in 3ms. Request failed: Internal error. (-32603).
Error data: "java.util.concurrent.CompletionException: java.lang.NullPointerException\n\tat java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)\n\tat java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)\n\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)\n\tat java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)\n\tat java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)\n\tat java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)\n\tat java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)\n\tat java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)\n\tat java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)\nCaused by: java.lang.NullPointerException\n\tat org.eclipse.lsp4xml.services.XMLFoldings.getFoldingRanges(XMLFoldings.java:62)\n\tat org.eclipse.lsp4xml.services.XMLLanguageService.getFoldingRanges(XMLLanguageService.java:94)\n\tat org.eclipse.lsp4xml.XMLTextDocumentService.lambda$foldingRange$9(XMLTextDocumentService.java:242)\n\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)\n\t... 6 more\n"


[Error - 9:49:03 AM] Request textDocument/foldingRange failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.eclipse.lsp4xml.services.XMLFoldings.getFoldingRanges(XMLFoldings.java:62)
	at org.eclipse.lsp4xml.services.XMLLanguageService.getFoldingRanges(XMLLanguageService.java:94)
	at org.eclipse.lsp4xml.XMLTextDocumentService.lambda$foldingRange$9(XMLTextDocumentService.java:242)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more

[Trace - 9:49:03 AM] Sending request 'textDocument/documentSymbol - (70)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/fbricon/Downloads/sample-resources%203/multiple_namespaces/service.xsd"
    }
}


[Trace - 9:49:03 AM] Received response 'textDocument/documentSymbol - (70)' in 2ms. Request failed: Internal error. (-32603).
Error data: "java.util.concurrent.CompletionException: java.lang.NullPointerException\n\tat java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)\n\tat java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)\n\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)\n\tat java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)\n\tat java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)\n\tat java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)\n\tat java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)\n\tat java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)\n\tat java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)\nCaused by: java.lang.NullPointerException\n\tat org.eclipse.lsp4xml.commons.LanguageModelCache.get(LanguageModelCache.java:56)\n\tat org.eclipse.lsp4xml.XMLTextDocumentService.getXMLDocument(XMLTextDocumentService.java:131)\n\tat org.eclipse.lsp4xml.XMLTextDocumentService.lambda$documentSymbol$5(XMLTextDocumentService.java:175)\n\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)\n\t... 6 more\n"


[Error - 9:49:03 AM] Request textDocument/documentSymbol failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.eclipse.lsp4xml.commons.LanguageModelCache.get(LanguageModelCache.java:56)
	at org.eclipse.lsp4xml.XMLTextDocumentService.getXMLDocument(XMLTextDocumentService.java:131)
	at org.eclipse.lsp4xml.XMLTextDocumentService.lambda$documentSymbol$5(XMLTextDocumentService.java:175)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more

[Trace - 9:49:04 AM] Sending request 'textDocument/documentLink - (71)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/fbricon/Downloads/sample-resources%203/multiple_namespaces/service.xsd"
    }
}


[Trace - 9:49:04 AM] Received response 'textDocument/documentLink - (71)' in 1ms.
Result: []


[Trace - 9:49:32 AM] Sending request 'textDocument/codeAction - (72)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/fbricon/Downloads/sample-resources%203/multiple_namespaces/service.xsd"
    },
    "range": {
        "start": {
            "line": 1,
            "character": 7
        },
        "end": {
            "line": 7,
            "character": 16
        }
    },
    "context": {
        "diagnostics": []
    }
}


[Trace - 9:49:32 AM] Received response 'textDocument/codeAction - (72)' in 3ms. Request failed: Internal error. (-32603).
Error data: "java.util.concurrent.CompletionException: java.lang.NullPointerException\n\tat java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)\n\tat java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)\n\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)\n\tat java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)\n\tat java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)\n\tat java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)\n\tat java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)\n\tat java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)\n\tat java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)\nCaused by: java.lang.NullPointerException\n\tat org.eclipse.lsp4xml.commons.LanguageModelCache.get(LanguageModelCache.java:56)\n\tat org.eclipse.lsp4xml.XMLTextDocumentService.getXMLDocument(XMLTextDocumentService.java:131)\n\tat org.eclipse.lsp4xml.XMLTextDocumentService.lambda$codeAction$12(XMLTextDocumentService.java:259)\n\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)\n\t... 6 more\n"


[Error - 9:49:32 AM] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.eclipse.lsp4xml.commons.LanguageModelCache.get(LanguageModelCache.java:56)
	at org.eclipse.lsp4xml.XMLTextDocumentService.getXMLDocument(XMLTextDocumentService.java:131)
	at org.eclipse.lsp4xml.XMLTextDocumentService.lambda$codeAction$12(XMLTextDocumentService.java:259)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more

[Trace - 9:49:32 AM] Sending request 'textDocument/codeAction - (73)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/fbricon/Downloads/sample-resources%203/multiple_namespaces/service.xsd"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 7,
            "character": 16
        }
    },
    "context": {
        "diagnostics": []
    }
}


[Trace - 9:49:32 AM] Received response 'textDocument/codeAction - (73)' in 3ms. Request failed: Internal error. (-32603).
Error data: "java.util.concurrent.CompletionException: java.lang.NullPointerException\n\tat java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)\n\tat java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)\n\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)\n\tat java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)\n\tat java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)\n\tat java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)\n\tat java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)\n\tat java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)\n\tat java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)\nCaused by: java.lang.NullPointerException\n\tat org.eclipse.lsp4xml.commons.LanguageModelCache.get(LanguageModelCache.java:56)\n\tat org.eclipse.lsp4xml.XMLTextDocumentService.getXMLDocument(XMLTextDocumentService.java:131)\n\tat org.eclipse.lsp4xml.XMLTextDocumentService.lambda$codeAction$12(XMLTextDocumentService.java:259)\n\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)\n\t... 6 more\n"


[Error - 9:49:32 AM] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.eclipse.lsp4xml.commons.LanguageModelCache.get(LanguageModelCache.java:56)
	at org.eclipse.lsp4xml.XMLTextDocumentService.getXMLDocument(XMLTextDocumentService.java:131)
	at org.eclipse.lsp4xml.XMLTextDocumentService.lambda$codeAction$12(XMLTextDocumentService.java:259)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more
```

Content of document:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://service" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://service">
    <complexType name="service">
        <attribute name="name" type="string" use="required"></attribute>
                  <attribute name="description" type="string" use="required"></attribute>
    </complexType>
    <element name="service" type="tns:service"></element>
</schema>       
```

**Comment by fbricon** [comment]
looks like a call to didChangeConfiguration flushes the document cache, which is the source of those NPEs

**Comment by angelozerr** [comment]
https://github.com/angelozerr/lsp4xml/commit/13a8d14d5fef08a43bb24654cdd2b73b3a4974a9 should fix your problem.

**Comment by fbricon** [comment]
Works now. Thanks @angelozerr

**Comment by angelozerr** [comment]
> Works now. Thanks @angelozerr

Cool, sorry for the disturb with my incremental work.
