### ISSUE TITLE
Emmet extension tests fail when running with JDK 11

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#219]
See:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest
Warning: Nashorn engine is planned to be removed from a future JDK release
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
	at org.eclipse.lsp4xml.extensions.emmet.emmetio.extract.ExtractAbbreviation.extractAbbreviation(ExtractAbbreviation.java:68)
	at org.eclipse.lsp4xml.extensions.emmet.utils.EmmetHelper.extract(EmmetHelper.java:159)
	at org.eclipse.lsp4xml.extensions.emmet.utils.EmmetHelper.extractAbbreviation(EmmetHelper.java:148)
	at org.eclipse.lsp4xml.extensions.emmet.utils.EmmetHelper.doComplete(EmmetHelper.java:59)
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionParticipant.onXMLContent(EmmetCompletionParticipant.java:32)
	at org.eclipse.lsp4xml.services.XMLCompletions.collectInsideContent(XMLCompletions.java:518)
	at org.eclipse.lsp4xml.services.XMLCompletions.doComplete(XMLCompletions.java:204)
	at org.eclipse.lsp4xml.services.XMLLanguageService.doComplete(XMLLanguageService.java:98)
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest.testCompletionFor(EmmetCompletionTest.java:65)
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest.testCompletionFor(EmmetCompletionTest.java:105)
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest.testHTMLAttributeNameCompletion(EmmetCompletionTest.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
	at org.eclipse.lsp4xml.extensions.emmet.emmetio.extract.ExtractAbbreviation.extractAbbreviation(ExtractAbbreviation.java:68)
	at org.eclipse.lsp4xml.extensions.emmet.utils.EmmetHelper.extract(EmmetHelper.java:159)
	at org.eclipse.lsp4xml.extensions.emmet.utils.EmmetHelper.extractAbbreviation(EmmetHelper.java:148)
	at org.eclipse.lsp4xml.extensions.emmet.utils.EmmetHelper.doComplete(EmmetHelper.java:59)
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionParticipant.onXMLContent(EmmetCompletionParticipant.java:32)
	at org.eclipse.lsp4xml.services.XMLCompletions.collectInsideContent(XMLCompletions.java:518)
	at org.eclipse.lsp4xml.services.XMLCompletions.doComplete(XMLCompletions.java:204)
	at org.eclipse.lsp4xml.services.XMLLanguageService.doComplete(XMLLanguageService.java:98)
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest.testCompletionFor(EmmetCompletionTest.java:65)
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest.testCompletionFor(EmmetCompletionTest.java:105)
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest.testHTMLElementCompletion(EmmetCompletionTest.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[ERROR] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 15.968 s <<< FAILURE! - in org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest
[ERROR] testHTMLAttributeNameCompletion(org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest)  Time elapsed: 15.813 s  <<< FAILURE!
java.lang.AssertionError: a>b[c] should only existing once: Actual:  expected:<1> but was:<0>
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest.assertCompletion(EmmetCompletionTest.java:93)
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest.testCompletionFor(EmmetCompletionTest.java:82)
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest.testCompletionFor(EmmetCompletionTest.java:105)
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest.testHTMLAttributeNameCompletion(EmmetCompletionTest.java:46)

[ERROR] testHTMLElementCompletion(org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest)  Time elapsed: 0.072 s  <<< FAILURE!
java.lang.AssertionError: a>b should only existing once: Actual:  expected:<1> but was:<0>
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest.assertCompletion(EmmetCompletionTest.java:93)
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest.testCompletionFor(EmmetCompletionTest.java:82)
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest.testCompletionFor(EmmetCompletionTest.java:105)
	at org.eclipse.lsp4xml.extensions.emmet.participants.EmmetCompletionTest.testHTMLElementCompletion(EmmetCompletionTest.java:40)

[INFO] Running org.eclipse.lsp4xml.extensions.emmet.emmetio.expand.ExpandAbbreviationTest
Warning: Nashorn engine is planned to be removed from a future JDK release
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.137 s - in org.eclipse.lsp4xml.extensions.emmet.emmetio.expand.ExpandAbbreviationTest
[INFO] Running org.eclipse.lsp4xml.extensions.emmet.emmetio.extract.ExtractAbbreviationTest
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
	at org.eclipse.lsp4xml.extensions.emmet.emmetio.extract.ExtractAbbreviation.extractAbbreviation(ExtractAbbreviation.java:68)
	at org.eclipse.lsp4xml.extensions.emmet.emmetio.extract.ExtractAbbreviationTest.testExtract(ExtractAbbreviationTest.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.013 s <<< FAILURE! - in org.eclipse.lsp4xml.extensions.emmet.emmetio.extract.ExtractAbbreviationTest
[ERROR] testExtract(org.eclipse.lsp4xml.extensions.emmet.emmetio.extract.ExtractAbbreviationTest)  Time elapsed: 0.012 s  <<< ERROR!
java.lang.NullPointerException
	at org.eclipse.lsp4xml.extensions.emmet.emmetio.extract.ExtractAbbreviationTest.testExtract(ExtractAbbreviationTest.java:13)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   EmmetCompletionTest.testHTMLAttributeNameCompletion:46->testCompletionFor:105->testCompletionFor:82->assertCompletion:93 a>b[c] should only existing once: Actual:  expected:<1> but was:<0>
[ERROR]   EmmetCompletionTest.testHTMLElementCompletion:40->testCompletionFor:105->testCompletionFor:82->assertCompletion:93 a>b should only existing once: Actual:  expected:<1> but was:<0>
[ERROR] Errors:
[ERROR]   ExtractAbbreviationTest.testExtract:13 NullPointer
[INFO]
[ERROR] Tests run: 5, Failures: 2, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for lsp4xml 0.0.3-SNAPSHOT:
[INFO]
[INFO] lsp4xml ............................................ SUCCESS [  0.148 s]
[INFO] org.eclipse.lsp4xml ................................ SUCCESS [ 16.554 s]
[INFO] lsp4xml-extensions ................................. SUCCESS [  0.013 s]
[INFO] org.eclipse.lsp4xml.extensions.emmet ............... FAILURE [ 28.727 s]
[INFO] org.eclipse.lsp4xml.extensions.web ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  45.579 s
[INFO] Finished at: 2018-11-13T09:40:33-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test (default-test) on project org.eclipse.lsp4xml.extensions.emmet: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/fbricon/Dev/projects/lsp4xml/extensions/org.eclipse.lsp4xml.extensions.emmet/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
```

**Comment by angelozerr** [comment]
Before working on Emmet etxtension, we must clarify a thing:

 * do we must embed a Nashorm or other JS engine to support in the future Java 11?
 * do we must rewrite emet js in Java?

**Comment by fbricon** [comment]
I really don't want us to spend time on emmet support at this point, it's very, very low on my list of priorities. I don't see the added value of emmet compared to completion support via schema.

So if it was up to me, I'd drop emmet support from the core repo at that point, if it prevents the build from running. Now this is your project. 

FTR, Javascript support from now on should probably provided via [GraalVM](https://www.infoworld.com/article/3291322/javascript/oracle-switch-now-from-nashorn-javascript-engine-to-graalvm.html).

**Comment by angelozerr** [comment]
> I don't see the added value of emmet compared to completion support via schema.

My idea is to provide Emmet based on XML Schema and DTD, I think it could be a very cool feature (more than simple completion). 

For instance for pom.xml, you type 

`dependencies>` and it opens completion with

```
dependencies>dependency
dependencies>dependency>artifactId
dependencies>dependency>groupId
dependencies>dependency>version
```

when you apply `dependencies>dependency>version` it generates: all XML content.

**Comment by angelozerr** [comment]
> Now this is your project.

Wrong! It's our project!

> FTR, Javascript support from now on should probably provided via GraalVM.

Didn't know that, thank's for the info.
