### ISSUE TITLE
Codeactions not working in Sublime Text

### ISSUE THREAD

**Issue by AmjadHD** [angelozerr/lsp4xml#401]
Codeactions don't work (in sublime text at least), this is the log from sublime's [LSP](https://github.com/tomv564/LSP.git) client
```
LSP:  --> textDocument/codeAction
LSP:      [{'title': "Close with '/>'", 'arguments': ['file:///D:/Downloads/Archives/lsp4xml-master/org.eclipse.lsp4xml/pom.xml', 5, [{'range': {'end': {'character': 12, 'line': 7}, 'start': {'character': 12, 'line': 7}}, 'newText': '/>'}]], 'command': '_xml.applyCodeAction'}, {'title': "Close with '>'", 'arguments': ['file:///D:/Downloads/Archives/lsp4xml-master/org.eclipse.lsp4xml/pom.xml', 5, [{'range': {'end': {'character': 12, 'line': 7}, 'start': {'character': 12, 'line': 7}}, 'newText': '>'}]], 'command': '_xml.applyCodeAction'}, {'title': "Close with '></artifactId>'", 'arguments': ['file:///D:/Downloads/Archives/lsp4xml-master/org.eclipse.lsp4xml/pom.xml', 5, [{'range': {'end': {'character': 12, 'line': 7}, 'start': {'character': 12, 'line': 7}}, 'newText': '></artifactId>'}]], 'command': '_xml.applyCodeAction'}]
LSP:  --> workspace/executeCommand
server: mai 28, 2019 9:16:35 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
server: SEVERE: Internal error: java.lang.reflect.InvocationTargetException
server: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
server: at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
server: at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
server: at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
server: at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
server: at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
server: at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
server: at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
server: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
server: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
server: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
server: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
server: at java.base/java.lang.Thread.run(Thread.java:835)
server: Caused by: java.lang.reflect.InvocationTargetException
server: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
server: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
server: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
server: at java.base/java.lang.reflect.Method.invoke(Method.java:567)
server: at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
server: ... 11 more
server: Caused by: java.lang.UnsupportedOperationException
server: at org.eclipse.lsp4j.services.WorkspaceService.executeCommand(WorkspaceService.java:40)
server: ... 16 more
server: 
LSP:      None
```
## Steps to reproduce
- open an xml file (e.g https://github.com/angelozerr/lsp4xml/blob/master/pom.xml)
- remove a closing `>`

**Comment by fbricon** [comment]
lsp4xml sends an _xml.applyCodeAction command back to the client. It should checks the client supports such command before sending back code actions. Even better, it should return code actions that don't require specific client support in the first place.

**Comment by AmjadHD** [comment]
https://github.com/tomv564/LSP/pull/567

**Comment by AmjadHD** [comment]
it is working now, you are free to close this if you want.

**Comment by angelozerr** [comment]
@AmjadHD thank's for the feedback and glad it works for you now.
