### ISSUE TITLE
LoggerTest fails on Windows OS

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#46]
In Windows OS, when I execute it, I have this error:

```
Running org.eclipse.lsp4xml.utils.LoggerTest
août 09, 2018 4:52:10 PM org.eclipse.lsp4xml.utils.LoggerTest testLogCreated
GRAVE: @@Log Message@@
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
assertTestFormatting(org.eclipse.lsp4xml.utils.LoggerTest)  Time elapsed: 0.001 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[Sep 16, 1997 04:05:05 org.my.test.Class mySourceMethod()
Message: Formatting Log Message
	at declaringClass.methodName(fileName.java:1)
	at declaringClass2.methodName2.drl.java(fileName2.java:2)
	at declaringClass.methodName.apk.java(fileName:3)]
> but was:<[sept. 16, 1997 04:05:05 org.my.test.Class mySourceMethod()
Message: Formatting Log Message
	at declaringClass.methodName(fileName.java:1)
	at declaringClass2.methodName2.drl.java(fileName2.java:2)
	at declaringClass.methodName.apk.java(fileName:3)
]
>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.eclipse.lsp4xml.utils.LoggerTest.assertTestFormatting(LoggerTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

@fbricon @NikolasKomonen could you fix this problem please? It seems that date are hard coded in the JUnit test. Thanks!

**Comment by angelozerr** [comment]
Sorry I have now the problem:
```

Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
assertTestFormatting(org.eclipse.lsp4xml.utils.LoggerTest)  Time elapsed: 0.001 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...rmatting Log Message[
	at declaringClass.methodName(fileName.java:1)
	at declaringClass2.methodName2.drl.java(fileName2.java:2)
	at declaringClass.methodName.apk.java(fileName:3)]
> but was:<...rmatting Log Message[
	at declaringClass.methodName(fileName.java:1)
	at declaringClass2.methodName2.drl.java(fileName2.java:2)
	at declaringClass.methodName.apk.java(fileName:3)
]
>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.eclipse.lsp4xml.utils.LoggerTest.assertTestFormatting(LoggerTest.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by fbricon** [comment]
this is a different problem. My guess is line ending comparison is the culprit. I believe the test expects hard-coded `\n`, instead of using the system line delimiter

**Comment by angelozerr** [comment]
Yes I think it is that.
